### ISSUE TITLE
no data within backbone.js app

### ISSUE THREAD

**Issue by dgirgenti** [adlawson/nodejs-langs#4]
I was in the middle of working on a project earlier today and quickly needed to turn 'en' into 'English', 'it' into 'Italian', etc. 

Installed langs 1.0.2 with npm, did a ```var langs = require('langs');``` and couldn't get it to return anything from a call to langs.where().

```
langs.where("1", "ko")
--> undefined
langs.where("1", "en")
--> undefined
langs.where("1", "it")
--> undefined
```

It looks like `langs` is an object with all the right methods, but there's no data.

```
langs.all()
---> Object (empty)
langs.names()
---> Array[0]
```

There are no console errors/warnings when I do any of these calls.

My backbone app doesn't do anything that breaks any other npm library like this.

**Comment by dgirgenti** [comment]
It works as expected in the node shell and on runkit

**Comment by Visya** [comment]
The issue here is with `require('./data.json')`. It does not play well with webpack and browserify.

**Comment by dgirgenti** [comment]
Good catch. I am using webpack here

**Comment by Visya** [comment]
You can try add `json-loader` to Webpack.
It does not work for me though. I think because I don't create a bundle.
